-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id integer NOT NULL DEFAULT nextval('address_id_seq'::regclass),
    state character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    house_number character varying(255) COLLATE pg_catalog."default",
    landmark character varying(255) COLLATE pg_catalog."default",
    pin_code integer NOT NULL,
    street_area character varying(255) COLLATE pg_catalog."default",
    admin_admin_code character varying(255) COLLATE pg_catalog."default",
    employee_employee_code character varying(255) COLLATE pg_catalog."default",
    manager_manager_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT address_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.admin
(
    admin_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    marital_status character varying(255) COLLATE pg_catalog."default",
    mobile_number integer NOT NULL,
    nationality character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT admin_pkey PRIMARY KEY (admin_code)
);

CREATE TABLE IF NOT EXISTS public.designation
(
    id integer NOT NULL DEFAULT nextval('designation_id_seq'::regclass),
    designation_title character varying(255) COLLATE pg_catalog."default",
    short_designation character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT designation_pkey PRIMARY KEY (id),
    CONSTRAINT uk_2kdgdyp075tiuubu27hpo5i9r UNIQUE (designation_title)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    active_projects integer NOT NULL,
    completed_projects integer NOT NULL,
    date_of_birth character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    marital_status character varying(255) COLLATE pg_catalog."default",
    mobile_number integer NOT NULL,
    nationality character varying(255) COLLATE pg_catalog."default",
    skills bytea,
    user_id integer,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_code)
);

CREATE TABLE IF NOT EXISTS public.manager
(
    manager_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    active_projects integer NOT NULL,
    completed_projects integer NOT NULL,
    date_of_birth character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    marital_status character varying(255) COLLATE pg_catalog."default",
    mobile_number integer NOT NULL,
    nationality character varying(255) COLLATE pg_catalog."default",
    skills bytea,
    user_id integer,
    CONSTRAINT manager_pkey PRIMARY KEY (manager_code)
);

CREATE TABLE IF NOT EXISTS public.project
(
    id integer NOT NULL DEFAULT nextval('project_id_seq'::regclass),
    applied integer NOT NULL,
    date_of_creation character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    domain character varying(255) COLLATE pg_catalog."default",
    experience integer NOT NULL,
    image character varying(255) COLLATE pg_catalog."default",
    last_date_to_apply character varying(255) COLLATE pg_catalog."default",
    location character varying(255) COLLATE pg_catalog."default",
    required_employee integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    manager_manager_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT project_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.project_employee
(
    projects_id integer NOT NULL,
    employee_employee_code character varying(255) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id integer NOT NULL,
    role_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.skills
(
    id integer NOT NULL DEFAULT nextval('skills_id_seq'::regclass),
    skill character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT skills_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    id integer NOT NULL DEFAULT nextval('user_role_id_seq'::regclass),
    role_role_id integer,
    user_id integer,
    CONSTRAINT user_role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_total
(
    id integer NOT NULL DEFAULT nextval('user_total_id_seq'::regclass),
    date_of_joining character varying(255) COLLATE pg_catalog."default",
    designation character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    middle_name character varying(255) COLLATE pg_catalog."default",
    office_location character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    probation_period integer NOT NULL,
    CONSTRAINT user_total_pkey PRIMARY KEY (id),
    CONSTRAINT uk_rkkbsv93tijxikqj1aarpetrn UNIQUE (email)
);

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fkbscngj4iruc50rf8ehw4f5xyx FOREIGN KEY (manager_manager_code)
    REFERENCES public.manager (manager_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fkqfdyqp8m482foyryd1f6722a FOREIGN KEY (employee_employee_code)
    REFERENCES public.employee (employee_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fkrvf6kuith47it8r39ixcsx52e FOREIGN KEY (admin_admin_code)
    REFERENCES public.admin (admin_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.admin
    ADD CONSTRAINT fk71qficl76upmapaivm8h5o80a FOREIGN KEY (user_id)
    REFERENCES public.user_total (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fkomngkjxpiw2epuvhap787jst5 FOREIGN KEY (user_id)
    REFERENCES public.user_total (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.manager
    ADD CONSTRAINT fk4pl9d9igwlrj264u4ypy9t33y FOREIGN KEY (user_id)
    REFERENCES public.user_total (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project
    ADD CONSTRAINT fkd88x3hx0t1pcy862h301h5fge FOREIGN KEY (manager_manager_code)
    REFERENCES public.manager (manager_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_employee
    ADD CONSTRAINT fk6onfa8jykxc30c47cj0ovw869 FOREIGN KEY (employee_employee_code)
    REFERENCES public.employee (employee_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_employee
    ADD CONSTRAINT fko8tuufttvxdkddrgq026nvhte FOREIGN KEY (projects_id)
    REFERENCES public.project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fk7u21823ktfhu9bmx2350x6n8s FOREIGN KEY (role_role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkc5eca0grhra21k3onahqrfel0 FOREIGN KEY (user_id)
    REFERENCES public.user_total (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;